bdmanager/bdmanager/urls.py
from django.contrib import admin
from django.urls import path,include
from django.views.generic.base import TemplateView # new

urlpatterns = [
    path("", TemplateView.as_view(template_name="home.html"), name="home"),
    path("admin/", admin.site.urls),
    path("users/", include("users.urls")),
    path("users/", include("django.contrib.auth.urls")),
    path('projectmanager/', include('projectmanager.urls')),
]

bdmanager/users/urls.py
from django.urls import path

from users.views import SignUpView

urlpatterns = [
    path("signup/", SignUpView.as_view(), name="signup"),
]

bdmanager/projectmanager/models.py
from django.db import models
from users.models import CustomUser
from django_countries.fields import CountryField
from djmoney.models.fields import MoneyField



# Create your models here.


class Project(models.Model):
    SURVEY_TYPE = (
        ('2D', '2D'),
        ('3D-S', '3D Streamer'),
        ('3D-O', '3D OBN'),
        ('4D-S', '4D Streamer'),
        ('4D-O', '4D OBN'),
        ('OBNL', 'OBN Long Offset'),
        ('HiRes', 'Hi-Res'),
        )
    
    PROJECT_TYPE = (
        ('Repro', 'Reprocessing'),
        ('New Acquisition', 'New Acquisition'),
        )
    
    STATUS = (('Ongoing', 'Ongoing'), ('Completed', 'Completed'),('Cancelled', 'Cancelled'),
              ('Development', 'Development'))
    
    PARTNERS = (('BGP', 'BGP'), ('CGG', 'CGG'), ('SWG', 'Shearwater'), ('PGS', 'PGS'),('SLB', 'SLB'),
                ('COSL','COSL'),('Searcher','Searcher'))
    
    permit = models.ForeignKey('Permit', on_delete=models.CASCADE, related_name='projects')    
    name = models.CharField(max_length=100)
    status = models.CharField(max_length=15, choices=STATUS)
    country = CountryField()
    survey_type = models.CharField(max_length=6, choices=SURVEY_TYPE)
    project_type = models.CharField(max_length=15, choices=PROJECT_TYPE)
    creator = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    project_size = models.DecimalField(max_digits=10, decimal_places=2,default=0.00)
    # Partners section
    # has_partners = models.BooleanField(default=False)
    partner_1 = models.CharField(max_length=10, choices=PARTNERS, blank=True, null=True, default=None)
    partner_2 = models.CharField(max_length=10, choices=PARTNERS, blank=True, null=True, default=None)
    partner_3 = models.CharField(max_length=10, choices=PARTNERS, blank=True, null=True, default=None)
    partner_share = models.DecimalField(max_digits=5, decimal_places=4, default=1)  # Field for partner share
    
        
    def calculate_partner_share(self):
        partner_count = bool(self.partner_1) + bool(self.partner_2) + bool(self.partner_3) + 1
        return 1 / partner_count if partner_count > 0 else 1

    def save(self, *args, **kwargs):
        self.partner_share = self.calculate_partner_share()  # Update partner_share before saving
        super().save(*args, **kwargs)
    
       
    start_date = models.DateField()
    end_date = models.DateField()
    description = models.TextField()
    cost = MoneyField(max_digits=10, decimal_places=2, default_currency='USD', blank=True, null=True)
    
    def __str__(self):
        return self.name

class Permit(models.Model):
    REGULATORS = (
        ("CNH", "CNH (Mexico)"),
        ("ANP", "ANP (Brazil)"),
        ("ANH", "ANH (Colombia)"),
        ("Staatsolie", "Staatsolie (Suriname)"),
        ("ANCAP", "ANCAP (Uruguay)"),
        ("MME", "MME (Brazil)"),
        ("SNE", "SNE (Argentina)"),
    )
    
    name = models.CharField(max_length=100)
    country = CountryField()
    regulator = models.CharField(max_length=10, choices=REGULATORS)
    creator = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    start_date = models.DateField()
    end_date = models.DateField()
    description = models.TextField()
    
    def __str__(self):
        return self.name
    
 
# The Sale class represents a sale in a project, with various attributes such as company, owner,
# status, probability, license area, unit rate, estimated value, weighted value, and sale date.
class Sale(models.Model):
    COMPANIES = (
        ("XOM", "ExxonMobil"),("CVX", "Chevron"),("ECP", "Ecopetrol"),("PBR", "Petrobras"),("RDS", "Shell"),
        ("PEMEX", "Pemex"),("Petronas", "Petronas"), ("BP", "BP"), ("TTE", "TotalEnergies"),("Equinor", "Equinor"),
        ("YPF", "YPF"),("Apache", "Apache"),("Eni", "Eni"),("Repsol", "Repsol"),("OGX", "OGX"),("PetroSA", "PetroSA"),
        ("CNOOC", "CNOOC"),("ONGC", "ONGC"),("NNPC", "NNPC"), ("PetroChina", "PetroChina"),("PTTEP", "PTTEP"),
        ("Sinopec", "Sinopec"),("Inpex", "Inpex"),("JOGMEC", "JOGMEC"),("Mubadala", "Mubadala"),("Qatar Petroleum", "Qatar Petroleum"),
        ("Kuwait Petroleum", "Kuwait Petroleum"),("KrisEnergy", "KrisEnergy"),("PetroVietnam", "PetroVietnam"),
        ("Woodside", "Woodside"),("Hess", "Hess"),("OMV", "OMV"),("CEPSA", "CEPSA")
    )
    
    STATUS = (('Quoted','Quoted'),('Purchased','Purchased'),('Deferred','Deferred'),('Cancelled','Cancelled'))
    project = models.ForeignKey('Project', on_delete=models.CASCADE, related_name='sales')
    company = models.CharField(max_length=16, choices=COMPANIES)
    owner = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    status = models.CharField(max_length=10, choices=STATUS)
    probability = models.DecimalField(max_digits=6, decimal_places=4, default=0.0)
    license_area = models.DecimalField(max_digits=10, decimal_places=2,default=0.00)
    unit_rate = MoneyField(max_digits=10, decimal_places=2, default_currency='USD', blank=True, null=True)
    estimated_value = MoneyField(max_digits=10, decimal_places=2, default_currency='USD', blank=True, null=True)
    weighted_value = MoneyField(max_digits=10, decimal_places=2, default_currency='USD', blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)    
    sale_date = models.DateField()
    tgs_net_value = MoneyField(max_digits=10, decimal_places=2, default_currency='USD', blank=True, null=True)
    
    
            

bdmanager/templates/base.html
<!-- templates/base.html -->

<!DOCTYPE html>
<html>
<head>

    <meta charset="utf-8">
  <title>{% block title %}BDManager{% endblock %}</title>
  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
  {% load bootstrap5 %}
  {% bootstrap_css %}

</head>
<body>

  {% bootstrap_messages %}
  
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">TGS BDManager</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="#">Dashboard</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Projects</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Leads</a>
                    </li>
                {% endif %}
            </ul>
            <ul class="navbar-nav">
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <span class="navbar-text me-3">Hello, {{ user.username }}</span>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'logout' %}">Logout</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'login' %}">Login</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>
  
  <div class="container mt-4">
      {% block content %}
      {% for message in messages %}
      <div class="alert alert-success alert-dismissible fade show" role="alert">
          {{ message }}
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
      {% endfor %}
      {% endblock %}
  </div>
  
  {% bootstrap_javascript %}
  <!-- Other scripts -->
  </body>
  </html>

bdmanager/templates/financials.html
<!-- templates/home.html -->
{% extends "base.html" %}

{% block title %}Home{% endblock %}

{% block content %}
    <h2>Financials</h2>
    
{% endblock %}

bdmanager/templates/home.html
<!-- templates/home.html -->
{% extends "base.html" %}

{% block title %}Home{% endblock %}

{% block content %}
    <h2>Home</h2>
    <p>Welcome to my awesome homepage.</p>
{% endblock %}

bdmanager/templates/permit_create.html
{% extends "base.html" %}

{% block title %}Create Permit - BDManager{% endblock %}

{% block content %}
<div class="row justify-content-center">
    <div class="col-md-6">
        <h2>Create Permit</h2>
        <form method="post">
            {% csrf_token %}
            <div class="mb-3">
                {{ form.name.label_tag }}
                {{ form.name }}
            </div>
            <div class="mb-3">
                {{ form.country.label_tag }}
                {{ form.country }}
            </div>
            <div class="mb-3">
                {{ form.regulator.label_tag }}
                {{ form.regulator }}
            </div>
            <div class="mb-3">
                {{ form.start_date.label_tag }}
                {{ form.start_date }}
            </div>
            <div class="mb-3">
                {{ form.end_date.label_tag }}
                {{ form.end_date }}
            </div>
            <div class="mb-3">
                {{ form.description.label_tag }}
                {{ form.description }}
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
</div>
{% endblock %}

bdmanager/templates/project_create.html
{% extends "base.html" %}

{% block title %}Create Project{% endblock %}

{% block content %}
<div class="row justify-content-center">
    <div class="col-md-8">
        <div class="card">
            <div class="card-body">
                <h2 class="card-title">Create Project</h2>
                <form method="post">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-md-6">
                            <div class="mb-3">
                                {{ form.permit.label_tag }}
                                {{ form.permit }}
                            </div>
                            <div class="mb-3">
                                {{ form.name.label_tag }}
                                {{ form.name }}
                            </div>
                            <div class="mb-3">
                                {{ form.status.label_tag }}
                                {{ form.status }}
                            </div>
                            <div class="mb-3">
                                {{ form.country.label_tag }}
                                {{ form.country }}
                            </div>
                            <div class="mb-3">
                                {{ form.survey_type.label_tag }}
                                {{ form.survey_type }}
                            </div>
                            <div class="mb-3">
                                {{ form.project_size.label_tag }}
                                {{ form.project_size }}
                            </div>
                            <div class="mb-3">
                                {{ form.description.label_tag }}
                                {{ form.description }}
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="mb-3">
                                {{ form.project_type.label_tag }}
                                {{ form.project_type }}
                            </div>
                            <div class="mb-3">
                                {{ form.start_date.label_tag }}
                                {{ form.start_date }}
                            </div>
                            <div class="mb-3">
                                {{ form.end_date.label_tag }}
                                {{ form.end_date }}
                            </div>
                            <div class="mb-3">
                                {{ form.cost.label_tag }}
                                {{ form.cost }}
                            </div>
                            <div class="mb-3">
                                {{ form.partner_1.label_tag }}
                                {{ form.partner_1 }}
                            </div>
                            <div class="mb-3">
                                {{ form.partner_2.label_tag }}
                                {{ form.partner_2 }}
                            </div>
                            <div class="mb-3">
                                {{ form.partner_3.label_tag }}
                                {{ form.partner_3 }}
                            </div>
                        </div>
                    </div>
                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

bdmanager/templates/sale_create.html
{% extends "base.html" %}

{% block title %}Create Sale{% endblock %}

{% block content %}
<div class="row justify-content-center">
    <div class="col-md-8">
        <div class="card">
            <div class="card-body">
                <h2 class="card-title">Create Sale</h2>
                <form method="post">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-md-6">
                            <div class="mb-3">
                                {{ form.project.label_tag }}
                                {{ form.project }}
                                <label for="project_size">Project Size:</label>
                                <input type="number" id="project_size" name="project_size" value="{{ project_size }}" disabled>
                                
                            </div>
                            <div class="mb-3">
                                {{ form.company.label_tag }}
                                {{ form.company }}
                            </div>
                            <div class="mb-3">
                                {{ form.status.label_tag }}
                                {{ form.status }}
                            </div>
                            <div class="mb-3">
                                {{ form.probability.label_tag }}
                                {{ form.probability }}
                            </div>
                            <div class="mb-3">
                                {{ form.sale_date.label_tag }}
                                {{ form.sale_date }}
                            </div>
                            <div class="mb-3">
                                {{ form.license_area.label_tag }}
                                {{ form.license_area }}                                
                                <div id="warning-message" class="alert alert-warning" role="alert" style="display: none;">
                                    The Selected License Volume is larger than the project size in the Database.
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">                            
                            <div class="mb-3" >
                                {{ form.unit_rate.label_tag }}
                                {{ form.unit_rate }}
                            </div>
                            <div class="mb-3" >
                                {{ form.estimated_value.label_tag }}
                                {{ form.estimated_value }}
                            </div>
                            <div class="mb-3" >
                                {{ form.weighted_value.label_tag }}
                                {{ form.weighted_value }}
                            </div>
                            <div class="mb-3" >
                                {{ form.tgs_net_value.label_tag }}
                                {{ form.tgs_net_value }}
                            </div>
                        </div>
                    </div>
                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>
            </div>
        </div>
    </div>
</div>

<script>
    $(document).ready(function() {
        var isInputHandlerAttached = false;
        
        function attachInputEventHandler() {
            $('[id^=id_probability], [id^=id_license_area], [id^=id_unit_rate], [id^=id_tgs_net_value]').on('input', function() {
                var licenseArea = parseFloat($('#id_license_area').val());
                var unitRate = parseFloat($('#id_unit_rate_0').val());
                var probability = parseFloat($('#id_probability').val());
                console.log('Probability:', probability);
                console.log('unitRate:', unitRate);
                var estimatedValueFieldID = '#id_estimated_value_0';
                var estimatedWeightedValueFieldID = '#id_weighted_value_0';
                var tgsNetValueFieldID = '#id_tgs_net_value_0';

                if (!isNaN(licenseArea) && !isNaN(unitRate)) {
                    var estimatedValue = licenseArea * unitRate;
                    $(estimatedValueFieldID).val(estimatedValue.toFixed(2));
                }
                if (!isNaN(licenseArea) && !isNaN(unitRate) && !isNaN(probability) && !isNaN(globalPartnerShare)) {
                    var prob = probability / 100;
                    var weightedValue = licenseArea * unitRate * prob 
                    $(estimatedWeightedValueFieldID).val(weightedValue.toFixed(2));
                }
                if (!isNaN(licenseArea) && !isNaN(unitRate) && !isNaN(probability) && !isNaN(globalPartnerShare)) {
                    var prob = probability / 100;
                    var tgsnetValue = licenseArea * unitRate * prob * globalPartnerShare;
                    $(tgsNetValueFieldID).val(tgsnetValue.toFixed(2));
                }
            });
        }

        $('#id_project').change(function() {
            var projectId = $(this).val();

            $.ajax({
                type: 'GET',
                url: '/projectmanager/get_partner_share/',
                headers: {
                    'X-Requested-With': 'XMLHttpRequest'
                },
                data: {
                    'project_id': projectId
                },
                success: function(response) {
                    var partnerShare = parseFloat(response.partner_share);
                    globalPartnerShare = partnerShare;

                    if (!isInputHandlerAttached) {
                        attachInputEventHandler();
                        isInputHandlerAttached = true;
                    } else {
                        // Trigger input event to recalculate values if the handler is already attached
                        $('[id^=id_probability]').trigger('input');
                    }
                },
                error: function(xhr, errmsg, err) {
                    console.log(errmsg);
                }
            });
        });
    });

    $(document).ready(function() {
        function checkProjectSize() {
            var projectId = $('#id_project').val();
            var licenseArea = parseFloat($('#id_license_area').val());
    
            $.ajax({
                type: 'GET',
                url: '/projectmanager/get_project_size/',
                data: {
                    'project_id': projectId
                },
                success: function(response) {
                    console.log('Response:', response);
                    var projectSizeFromDB = parseFloat(response.project_size);
                    $('#project_size').val(projectSizeFromDB);  // Set project size in the input field
    
                    if (!isNaN(licenseArea) && !isNaN(projectSizeFromDB) && licenseArea > projectSizeFromDB) {
                        $('#warning-message').show();  // Show warning message
                    } else {
                        $('#warning-message').hide();  // Hide warning message
                    }
                },
                error: function(xhr, errmsg, err) {
                    console.log(errmsg);
                }
            });
        }
    
        // Check when the project changes
        $('#id_project').change(checkProjectSize);
    
        // Check when the license area is changed
        $('#id_license_area').on('input', checkProjectSize);
    
        // Additionally, trigger the check initially if both project ID and license area have values
        var projectId = $('#id_project').val();
        var licenseArea = $('#id_license_area').val();
        if (projectId && licenseArea) {
            checkProjectSize();
        }
    });


</script>


{% endblock %}